local options = vim.opt

options.exrc = true
options.guicursor = ""
options.hidden = true
options.tabstop = 4
options.softtabstop = 4
options.shiftwidth = 4
options.expandtab = true
options.smartindent = true
options.number = true
options.wrap = true
options.mouse = "a"
options.undofile = true
options.incsearch = true
options.termguicolors = true
options.scrolloff = 8
options.sidescrolloff = 8
options.signcolumn = "yes"